export type RunLedgerMode = "backfill" | "explore" | "ingest";

export type RunLedgerSlice = {
  number: number;
  sinceDate: string;
  untilDate?: string;
};

type RunLedgerExpansionFields = {
  id: string;
  reason?: string;
  slice?: RunLedgerSlice;
  sourceStream: string;
  title?: string;
  type: "expansion";
  url?: string;
};

type RunLedgerExpansionEvent = RunLedgerExpansionFields &
  (
    | { outcome: "failed" | "ok" }
    | {
        /** Number of candidates represented by a skipped aggregate. */
        count?: number;
        outcome: "skipped";
      }
  );

export type RunLedgerEvent =
  | {
      counts: { deduplicated: number; fetched: number; new: number };
      error?: string;
      slice?: RunLedgerSlice;
      stream: string;
      type: "pull";
    }
  | RunLedgerExpansionEvent
  | {
      outcome: "failed" | "ok";
      reason?: string;
      serverId: string;
      target?: string;
      toolName: string;
      type: "escalation";
    }
  | {
      status: "dry" | "none" | "walking";
      type: "watermark";
      watermark: string;
    }
  | { message: string; type: "warning" };

export type RunLedger = {
  connectorId: string;
  events: RunLedgerEvent[];
  message: string;
  mode: RunLedgerMode;
  runId: string;
  startedAt: string;
  status: "error" | "skipped" | "success";
};

const MACHINE_GENERATED_NOTICE =
  "_Machine-generated by OpenWiki runs. Do not edit._";
const UNPARSEABLE_PAGE_NOTICE =
  "_The previous content of this page could not be parsed as a Run Ledger and is preserved below._";
const PRUNED_TRAILER_PATTERN =
  /\n\n(_Older runs pruned: only the most recent \d+ are kept on this page\._)$/u;

export function createNoWatermarkEvent(
  at: string,
): Extract<RunLedgerEvent, { type: "watermark" }> {
  return { status: "none", type: "watermark", watermark: at };
}

export function renderRunLedgerSection(ledger: RunLedger): string {
  const pulls = ledger.events.filter((event) => event.type === "pull");
  const expansions = ledger.events.filter(
    (event) => event.type === "expansion",
  );
  const escalations = ledger.events.filter(
    (event) => event.type === "escalation",
  );
  const warnings = ledger.events.filter((event) => event.type === "warning");
  const lines = [
    `## Run ${ledger.runId} — ${ledger.mode} — ${ledger.status === "error" ? "ERROR" : ledger.status}`,
    "",
    renderInlineText(ledger.message),
    `Started: ${ledger.startedAt}`,
    "",
    renderWatermark(ledger.events),
    "",
    "### Pulls",
    "",
    ...renderPulls(pulls),
    "",
    "### Content Expansion",
    "",
    ...renderExpansions(expansions),
    "",
    "### Escalations",
    "",
    ...renderEscalations(escalations),
  ];

  if (warnings.length > 0) {
    lines.push(
      "",
      "### Warnings",
      "",
      ...warnings.map((event) => `- ${renderInlineText(event.message)}`),
    );
  }

  return lines.join("\n");
}

export function upsertRunLedgerSection(
  existingPage: string | null,
  ledger: RunLedger,
  options: { maxRuns?: number } = {},
): string {
  const header = createPageHeader(ledger.connectorId);
  const maxRuns = Math.max(0, Math.floor(options.maxRuns ?? 20));
  const newSection = renderRunLedgerSection(ledger);
  const parsedPage = parseRunPage(existingPage, header);
  const preserveExistingPage =
    existingPage !== null &&
    existingPage.trim().length > 0 &&
    parsedPage === null;
  let sections: string[];

  if (!parsedPage) {
    sections = [newSection];
  } else {
    const existingIndex = parsedPage.sections.findIndex(
      (section) => readSectionRunId(section) === ledger.runId,
    );
    sections =
      existingIndex < 0
        ? [newSection, ...parsedPage.sections]
        : parsedPage.sections.map((section, index) =>
            index === existingIndex ? newSection : section,
          );
  }

  const retainedSections = sections.slice(0, maxRuns);
  const prunedTrailer =
    sections.length > retainedSections.length || parsedPage?.prunedTrailer
      ? `_Older runs pruned: only the most recent ${maxRuns} are kept on this page._`
      : undefined;
  let page =
    retainedSections.length > 0
      ? `${header}\n\n${retainedSections.join("\n\n")}`
      : header;

  if (prunedTrailer) {
    page += `\n\n${prunedTrailer}`;
  }
  if (preserveExistingPage) {
    page += `\n\n---\n\n${UNPARSEABLE_PAGE_NOTICE}\n\n${existingPage}`;
  }

  return page.endsWith("\n") ? page : `${page}\n`;
}

function renderWatermark(events: RunLedgerEvent[]): string {
  let watermark: Extract<RunLedgerEvent, { type: "watermark" }> | undefined;
  for (const event of events) {
    if (event.type === "watermark") {
      watermark = event;
    }
  }

  return watermark && watermark.status !== "none"
    ? `History provably covered back to ${watermark.watermark.slice(0, 10)} (${watermark.status}).`
    : "No Backfill watermark recorded yet.";
}

function renderPulls(
  pulls: Extract<RunLedgerEvent, { type: "pull" }>[],
): string[] {
  if (pulls.length === 0) {
    return ["No Pull events recorded for this run."];
  }

  return [
    "| Slice | Window | Stream | Fetched | New | Deduplicated | Note |",
    "| ---: | :--- | :--- | ---: | ---: | ---: | :--- |",
    ...pulls.map((pull) => {
      const slice = pull.slice ? String(pull.slice.number) : "—";
      const window = pull.slice
        ? `${pull.slice.sinceDate} → ${pull.slice.untilDate ?? "—"}`
        : "—";
      return `| ${slice} | ${window} | ${escapeTableCell(pull.stream)} | ${pull.counts.fetched} | ${pull.counts.new} | ${pull.counts.deduplicated} | ${escapeTableCell(pull.error ?? "")} |`;
    }),
  ];
}

function renderExpansions(
  expansions: Extract<RunLedgerEvent, { type: "expansion" }>[],
): string[] {
  if (expansions.length === 0) {
    return ["No Content Expansion in this run."];
  }

  const failed = expansions.filter((event) => event.outcome === "failed");
  const ok = expansions.filter((event) => event.outcome === "ok");
  const skipped = expansions.filter((event) => event.outcome === "skipped");
  const skippedGroups = groupSkippedExpansions(skipped);
  const skippedCount = skippedGroups.reduce(
    (count, group) => count + group.count,
    0,
  );
  const lines = [
    `ok ${ok.length} · failed ${failed.length} · skipped ${skippedCount}`,
  ];
  const attemptCount = ok.length + failed.length;

  if (attemptCount > 0 && failed.length === attemptCount) {
    lines.push(
      "",
      `> ⚠️ ALERT: all ${attemptCount} Content Expansion attempts failed — the wiki gained no document content this run.`,
    );
  }

  lines.push(
    ...failed.map(
      (event) =>
        `- FAILED ${renderExpansionLabel(event)} (${renderInlineText(event.sourceStream)}) — ${renderInlineText(event.reason ?? "reason not recorded")}`,
    ),
    ...ok.map(
      (event) =>
        `- ok ${renderExpansionLabel(event)} (${renderInlineText(event.sourceStream)})`,
    ),
    ...skippedGroups.map((group) =>
      group.hasCount
        ? `- skipped — ${renderInlineText(group.reason)} (${group.count} candidates)`
        : `- skipped ${group.count} — ${renderInlineText(group.reason)}`,
    ),
  );

  return lines;
}

function renderExpansionLabel(
  event: Extract<RunLedgerEvent, { type: "expansion" }>,
): string {
  const label = escapeMarkdownText(event.title ?? event.id);
  return event.url ? `[${label}](${event.url})` : label;
}

function groupSkippedExpansions(
  events: Extract<RunLedgerEvent, { outcome: "skipped"; type: "expansion" }>[],
): { count: number; hasCount: boolean; reason: string }[] {
  const groups = new Map<
    string,
    { count: number; hasCount: boolean; reason: string }
  >();

  for (const event of events) {
    const reason = event.reason ?? "reason not recorded";
    const existing = groups.get(reason);
    groups.set(reason, {
      count: (existing?.count ?? 0) + (event.count ?? 1),
      hasCount: existing?.hasCount || event.count !== undefined,
      reason,
    });
  }

  return [...groups.values()];
}

function renderEscalations(
  escalations: Extract<RunLedgerEvent, { type: "escalation" }>[],
): string[] {
  if (escalations.length === 0) {
    return ["No Escalations in this run."];
  }

  return escalations.map((event) => {
    const target = event.target ? ` — ${renderInlineText(event.target)}` : "";
    const outcome = event.outcome === "failed" ? "FAILED" : "ok";
    const reason = event.reason ? ` (${renderInlineText(event.reason)})` : "";
    return `- ${renderInlineText(event.toolName)} on ${renderInlineText(event.serverId)}${target} — ${outcome}${reason}`;
  });
}

function createPageHeader(connectorId: string): string {
  const title = connectorId
    .split("-")
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(" ");
  return `# ${title} Run Ledger\n\n${MACHINE_GENERATED_NOTICE}`;
}

function parseRunPage(
  existingPage: string | null,
  header: string,
): { prunedTrailer?: string; sections: string[] } | null {
  if (existingPage?.includes(UNPARSEABLE_PAGE_NOTICE)) {
    return null;
  }

  let normalizedPage = existingPage?.trimEnd() ?? "";
  const prunedTrailerMatch = PRUNED_TRAILER_PATTERN.exec(normalizedPage);
  const prunedTrailer = prunedTrailerMatch?.[1];
  if (prunedTrailerMatch?.index !== undefined) {
    normalizedPage = normalizedPage.slice(0, prunedTrailerMatch.index);
  }

  if (normalizedPage === header) {
    return {
      ...(prunedTrailer ? { prunedTrailer } : {}),
      sections: [],
    };
  }

  const prefix = `${header}\n\n`;
  if (!normalizedPage.startsWith(prefix)) {
    return null;
  }

  const remainder = normalizedPage.slice(prefix.length).trim();
  if (!remainder.startsWith("## Run ")) {
    return null;
  }

  const [first, ...rest] = remainder.split("\n## Run ");
  const sections = [first, ...rest.map((section) => `## Run ${section}`)];
  return sections.every(isRunLedgerSection)
    ? {
        ...(prunedTrailer ? { prunedTrailer } : {}),
        sections,
      }
    : null;
}

function isRunLedgerSection(section: string): boolean {
  return (
    readSectionRunId(section) !== undefined &&
    section.includes("\n### Pulls\n") &&
    section.includes("\n### Content Expansion\n") &&
    section.includes("\n### Escalations\n")
  );
}

function readSectionRunId(section: string): string | undefined {
  return /^## Run (.*?) — /u.exec(section)?.[1];
}

function escapeTableCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function escapeMarkdownText(value: string): string {
  return renderInlineText(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]");
}

function renderInlineText(value: string): string {
  return value.replace(/\r\n?|\n/gu, " ");
}
